### ISSUE TITLE
Etcd version

### ISSUE THREAD

**Issue by jadjay** [Ferlab-Ste-Justine/terraform-provider-etcd#1]
Hi,

I try your provider, it seems to be able to creat keys in etcd, but does it work with etcdv3 protocol (GRPC) ? 

Regards,

**Comment by Magnitus-** [comment]
Greetings,

sorry for not catching your inquiry earlier.

The provider doesn't use the grpc protocol directly, but rather leverages the official etcd client libraries (which use grpc underneat the hood). And yes, we're using it against etcd 3.4.x.

The provider has been pretty dependable so far. 

One caveat I noticed previously is that sometimes, if you create a larger volume of keys at once, we can get some old key version error (actually, haven't encountered that problem in a while now) which would mean that our automaton would need to run terraform apply more than once to get it to go through (but it would always go through on the second terraform apply). It hasn't been a show stopper though and our deadlines being what they are, its an issue I'll have to investigate post-production.

**Comment by Magnitus-** [comment]
I think the problem we were intermittently getting was due to this: https://github.com/etcd-io/etcd/issues/13300

we updated the client version to a version that has the fix outlined in the issue, so it is most likely resolved now.

**Comment by jadjay** [comment]
Thanks!
